#include <R.h>
#include <Rinternals.h>
#include <stdlib.h> // for NULL
#include <R_ext/Rdynload.h>


/* Section generated by pkgbuild, do not edit */
/* .Call calls */
extern SEXP c_rep(SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"c_rep", (DL_FUNC) &c_rep, 3},
    {NULL, NULL, 0}
};
/* End section generated by pkgbuild */

void R_init_repc(DllInfo *dll)
{
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
